services:
  db:
    image: postgres:15-alpine
    container_name: spy_cat_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spy_cat_agency
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spy_cat_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/spy_cat_agency
    depends_on:
      - db

volumes:
  postgres_data: