[project]
name = "testtask"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.11",
    "sqlmodel>=0.0.31",
    "uvicorn>=0.40.0",
]
